config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :user_activities

  resources :activities
  root to: 'activities#index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]  do
    resources :messages
  end

  resources :users_languages, only: [:create, :destroy]

  resources :match do
  member do
    put 'match_request'
    put 'match_request_accept'
    delete 'match_request_reject'
  end
end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', primary_key: :sender_id
  belongs_to :recipient, class_name: 'User', primary_key: :recipient_id

  # validates_presence_of :sender_id, :recipient_id, :email, :body
   validates_presence_of :body

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @sent_messages = @user.sent_messages
    @received_messages = @user.received_messages
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = current_user.sent_messages.build
    @users= User.all
  end

  def create
    @users = User.all
    @message = current_user.sent_messages.build(message_params)
    if @message.save
      flash[:success] = "Successfully sent!"
      redirect_to user_messages_path(current_user)
    else
      flash[:error] = "Whoops, something went wrong..."
      render 'new'
    end
  end

  def edit
    @message = Message.find(current_user)
  end

  def update
    @user = User.find(current_user)
    @message = Message.update(message_params)

    if @message.save
      redirect_to user_message_path(user_id: @user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id]).destroy
    flash[:success] = "Successfully deleted..."
    redirect_to user_messages_path(user_id: current_user.id)
  end

  private

  def message_params
    params.require(:message).permit(:recipient_id, :title, :body).merge(sender_id: current_user.id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div>
<%= f.label 'Choose recipient' %> <br>
  <%= f.select :recipient_id, @users.collect {|p| [ p.username, p.id ] } %>
  </div>
  <div>
    <%= f.text_field :title, placeholder: 'Enter subject' %>
  </div>
  <div>
    <%= f.text_area :body, placeholder: 'Type message here' %>
  </div>
  <div>
    <%= f.submit 'Send Message' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div class="small-6 small-centered small-centered columns">
  <div class="panel">

<div class="editmessage">

<section class="message-form">
  <h2> Edit message </h2>
    <%= render 'form' %>
</section>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>
</div>
</div>
</div>

app/views/messages/index.html.erb
<div class="small-6 small-centered small-centered columns">
<div class="panel">
<%= render 'common/flash' %>
<section class="inbox">
  <h2>My Inbox</h2>
  <div class="messages">
  <div class="sent">
    <h3> Sent (<%= current_user.sent_messages.count %>) </h3>
      <% current_user.sent_messages.each do |message| %>
        <h4><%=  message.title %></h4>
        <p> <%= message.body %></p>
        <%= link_to 'delete', user_message_path(user_id: current_user.id, id: message.id), method: :delete %>
      <% end %>
  </div>
  <div class="received">
    <h3> Recieved (<%= current_user.received_messages.count %>) </h3>
    <% current_user.received_messages.each do |message| %>
      <h4><%=  link_to message.title, user_message_path(user_id: message.recipient_id, id: message.id) %> </h4>
      <p><%= message.body %> </p>
       <%= link_to 'delete', user_message_path(user_id: current_user.id, id: message.id), method: :delete %>
    <% end %>
  </div>
  </div>
</section>
</div>
</div>

app/views/messages/new.html.erb
<div class="small-6 small-centered small-centered columns">
  <div class="panel">

<section class="newmessage">
  <h2> Send a message to your chosen FitBud! </h2>
    <%= render 'form' %>
</section>
<%# link_to 'Back', users_path %>
</div>
</div>

app/views/messages/show.html.erb
<div class="showmessage">

  <p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>
</div>