config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :user_activities

  resources :activities
  root to: 'activities#index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]  do
    resources :messages
  end

  resources :users_languages, only: [:create, :destroy]

  resources :match do
  member do
    put 'match_request'
    put 'match_request_accept'
    delete 'match_request_reject'
  end
end

end

app/models/user_activity.rb
class UserActivity < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity

  validates_presence_of :user_id, :activity_id
  validates_uniqueness_of :activity_id, scope: :user_id

end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController

  def create
    user = current_user
    activity = Activity.find(params[:activity_id])
    new_activity = current_user.user_activities.build(activity: activity)
    if new_activity.save
      flash[:success] = "Successfully added #{activity.name} as your favorite activity..."
      redirect_to activity_path(activity)
    elsif current_user.activities.find(activity)
       redirect_to activity_path(activity)
    else
      flash[:error] = "Whoops, something went wrong..."
      redirect_to activities_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @activity = activity.find(params[:id])

    @association = UsersActivity.remove_activity
  end

end

app/helpers/user_activities_helper.rb
module UserActivitiesHelper
end

app/views/user_activities/_form.html.erb
<%= form_for(@user_activity) do |f| %>
  <% if @user_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_activity.errors.count, "error") %> prohibited this user_activity from being saved:</h2>

      <ul>
      <% @user_activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br>
    <%= f.number_field :activity_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_activities/edit.html.erb
<div class="editactivities">

  <h1>Editing user_activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_activity %> |
<%= link_to 'Back', user_activities_path %>

</div>

app/views/user_activities/index.html.erb
<h1>Listing user_activities</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Activity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_activities.each do |user_activity| %>
      <tr>
        <td><%= user_activity.user_id %></td>
        <td><%= user_activity.activity_id %></td>
        <td><%= link_to 'Show', user_activity %></td>
        <td><%= link_to 'Edit', edit_user_activity_path(user_activity) %></td>
        <td><%= link_to 'Destroy', user_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User activity', new_user_activity_path %>

app/views/user_activities/new.html.erb
<h1>New user_activity</h1>

<%= render 'form' %>

<%= link_to 'Back', user_activities_path %>

app/views/user_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_activity.user_id %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @user_activity.activity_id %>
</p>

<%= link_to 'Edit', edit_user_activity_path(@user_activity) %> |
<%= link_to 'Back', user_activities_path %>