config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :user_activities

  resources :activities
  root to: 'activities#index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]  do
    resources :messages
  end

  resources :users_languages, only: [:create, :destroy]

  resources :match do
  member do
    put 'match_request'
    put 'match_request_accept'
    delete 'match_request_reject'
  end
end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_activities
  has_many :activities, through: :user_activities, foreign_key: :user_id


  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :matches
  has_many :partners, :through => :matches, :class_name =>'User'

  has_many :received_messages, class_name: 'Message', foreign_key: :recipient_id
  has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id

  validates_presence_of :username, :email, :location

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "fitbuddefault.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpeg", "image/gif", "image/png"]
  geocoded_by :address
  after_validation :geocode

  def admin?
    if self.admin
    end
  end

  def address
    [location, zip_code].compact.join(', ')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @users = User.all
    @partner = User.find(params[:id])
    @activities = Activity.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<div class="partnerinfo">
  <h2> <%= @partner.username.upcase %> </h2>
  <h4> wants a partner for: </h4>
  <ul>
    <% @partner.activities.each do |activity| %>
      <li> <%= activity.name %> </li>
    <% end %>
  </ul>
  <h4> lives in: </h4>
  <%= @partner.location %>

  <h4> Other information: </h4>
  <p> Age:<%= @partner.age %> <br>
  Goals:<%= @partner.goals %><br>
  About:<%= @partner.about_me %><br>
  Email: <%= @partner.email %> </p>

  <% if current_user == @partner %>
    <div>
      <h4> Add an activity: </h4>
      <ul>
        <% @activities.each do |activity| %>
          <% unless current_user.activities.include?(activity) %>
            <li> <%= link_to activity.name, user_activities_path(activity_id: activity.id), method: :post %> </li>
            <% end %>
        <% end %>
      </ul>
    </div>
    <h4> <% if current_user %><%= button_to 'Edit Profile', edit_user_registration_path(current_user), :class => "smallbutton", :method => :get %> </h4>
    <% end %>
     <% end %>
    <div class="smallbutton"> <h2> <%= button_to "Message to request user as a FitBud", new_user_message_path(@partner), :class => "smallbutton", :method => :get %><br />
      <%= button_to "My Profile", user_path(current_user) , :class => "smallbutton", :method => :get %><br /> </h2>
    </div>


</div>

app/views/users/show.html.erb
<%= render 'common/flash' %>
<!-- <section class="user-show"> -->
  <div class="small-6 small-centered small-centered columns">
  <div class="panel">
<div class="showuser">
<% if current_user %>
<%= image_tag current_user.avatar.url(:medium) %>
<% else %>
<%= image_tag @partner.avatar.url(:medium) %>
<% end %>
  <%= render 'info' %>
<!-- </section> -->
</div>
</div>
</div>