config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :user_activities

  resources :activities
  root to: 'activities#index'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:show]  do
    resources :messages
  end

  resources :users_languages, only: [:create, :destroy]

  resources :match do
  member do
    put 'match_request'
    put 'match_request_accept'
    delete 'match_request_reject'
  end
end

end

app/views/layouts/_header.html.erb
<header>
  <div class="left-header">
    <h1> <%= link_to 'FitBud', '/' %> </h1>
  </div>
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to 'sign out', sign_out_path, method: :delete %></li> |
      <li><%= link_to 'my profile', user_path(current_user) %></li> |
      <li><%= link_to 'browse', activities_path %></li> |
      <li> <%= link_to 'inbox', user_messages_path(user_id: current_user.id) %> </li>
    <% else %>
      <li> <%= link_to 'sign in', sign_in_path %> </li> |
      <li> <%= link_to 'sign up', sign_up_path %> </li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FitBud</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/activities">FitBud</a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="has-dropdown">
          <a href="#">Options</a>
          <ul class="dropdown">
          <% if user_signed_in? %>
            <li class="active"><%= link_to "My Profile", user_path(current_user) %></li>
            <li class="active"><a href="/activities">Browse Activities</a></li>
           <li class="active"><a href="/messages">Inbox</a></li>
           <li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

           <% else %>
           <li class="active"><%= link_to 'Sign up', new_user_registration_path %> </li>
            <li class="active"><%= link_to 'Login', new_user_session_path %> </li>
           <% end %>
         </ul>
        </li>
      </ul>
    </section>
  </nav>

  <%= yield %>
</div>
<div id="footer"> <div>About FitBud: FitBud is an app designed to match people up by an outdoor activity they would like to find a partner for.<br> Stay Fit while making a new Bud through FitBud!<br> Don't see your favorite activity? <a href="mailto:rmalik2788@gmail.com"> Contact us </a> | © 2014 DC WDI FitBud </div> </div>

</body>
</html>